# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM epinux/r-notebook

MAINTAINER Massimo Di Stefano  <epiesasha@me.com>

USER root


RUN apt-get clean && apt-get update && \
    apt-get install -y --no-install-recommends \
    package-name